### ISSUE TITLE
Transform

### ISSUE THREAD

**Issue by CarryWang** [CarryWang/Blog#5]
## perspective属性的两种书写

`perspective`属性有两种书写形式，一种用在舞台元素上（动画元素们的共同父辈元素）；第二种就是用在当前动画元素上，与transform的其他属性写在一起。如下代码示例：

```css

.stage {
    perspective: 600px;
}

```
以及：
```css

.stage .box {
    transform: perspective(600px) rotateY(45deg);
}

```
