### ISSUE TITLE
隐藏滚动条并保持滚动

### ISSUE THREAD

**Issue by CarryWang** [CarryWang/Blog#6]
**要隐藏滚动条很简单，css设置overflow:hidden就行了，但是你会发现设置了之后就无法滚动了，如何在隐藏滚动条的同时又保持滚动功能呢**

只需要这样：
```css

#parent{
    height: 100%;
    width: 100%;
    overflow: hidden;
}

#child{
    width: 100%;
    height: 100%;
    overflow-y: scroll;
    padding-right: 17px; /* 滚动条宽度一般为17px */
}

```

或者这样：

```css

#parent{
    height: 100%;
    width: 100%;
    overflow: hidden;
    position: relative;
}

#child{
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: -17px; /* 滚动条宽度一般为17px */
    overflow-y: scroll;
}

```
